services:
  cache-db:
    image: redis:7.2.5-alpine
    container_name: cache-redis-db
    restart: always
    env_file:
      - path: .env.docker
        required: true
    ports:
      - 6380:6379
    mem_limit: 512mb
    volumes:
      - ./compose/data/cache:/data
    networks:
      - localnet

  sql-db:
    image: postgres:18-alpine3.22
    container_name: sql-postgre-db
    restart: always
    env_file:
      - path: .env.docker
        required: true
    ports:
      - 5444:5432
    mem_limit: 1Gb
    volumes:
      - ./compose/data/sql:/var/lib/postgres/data
    networks:
      - localnet

  app:
    build: .
    container_name: app
    # restart: always
    depends_on:
      - cache-db
      - sql-db
    ports:
      - 3333:3333
    mem_limit: 2Gb
    volumes:
      - ./compose/data/app:/app
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
